// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::io::{BufRead, BufReader, Write};
use std::process::{Child, ChildStdin, ChildStdout, Stdio};
use std::sync::Arc;
use tauri::Emitter;
use tokio::sync::Mutex;

// ============================================================================
// Types
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandResult {
    pub success: bool,
    pub output: String,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanOptions {
    /// Unique identifier for this scan (generated by frontend)
    pub scan_id: String,
    /// Database name for storing scan results (e.g., "tab-{uuid}")
    pub db_name: String,
    /// Path to scan
    pub path: String,
    #[serde(default)]
    pub include_hidden: bool,
    #[serde(default = "default_batch_size")]
    pub batch_size: u32,
    #[serde(default)]
    pub disable_archives: bool,
}

fn default_batch_size() -> u32 {
    1000
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChecksumOptions {
    #[serde(default = "default_algorithm")]
    pub algorithm: String,
    #[serde(default)]
    pub each_file: bool,
}

fn default_algorithm() -> String {
    "xxhash64".to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportOptions {
    pub output_path: String,
    #[serde(default)]
    pub full_paths: bool,
    /// Database name to export from
    pub db_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryRequest {
    pub id: String,
    pub action: String,
    #[serde(flatten)]
    pub params: serde_json::Map<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PathValidationResult {
    pub valid: bool,
    pub is_directory: bool,
    pub readable: bool,
    pub exists: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryResponse {
    pub id: String,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

// ============================================================================
// Event Payloads (with scan_id for routing)
// ============================================================================

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanProgressEvent {
    pub scan_id: String,
    pub line: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanErrorEvent {
    pub scan_id: String,
    pub line: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanCompleteEvent {
    pub scan_id: String,
    pub success: bool,
}

// ============================================================================
// Query Session Management
// ============================================================================

/// Manages the long-running query process for interactive database access
pub struct QuerySession {
    process: Child,
    stdin: ChildStdin,
    stdout: BufReader<ChildStdout>,
    pub run_id: String,
}

impl QuerySession {
    /// Send a query and wait for the response
    fn query(&mut self, request: &QueryRequest) -> Result<QueryResponse, String> {
        // Serialize and send request
        let json = serde_json::to_string(request)
            .map_err(|e| format!("Failed to serialize request: {}", e))?;

        writeln!(self.stdin, "{}", json)
            .map_err(|e| format!("Failed to write to query process: {}", e))?;

        self.stdin
            .flush()
            .map_err(|e| format!("Failed to flush query process stdin: {}", e))?;

        // Read response
        let mut response_line = String::new();
        self.stdout
            .read_line(&mut response_line)
            .map_err(|e| format!("Failed to read from query process: {}", e))?;

        if response_line.is_empty() {
            return Err("Query process closed unexpectedly".to_string());
        }

        // Parse response
        serde_json::from_str(&response_line)
            .map_err(|e| format!("Failed to parse query response: {}", e))
    }

    /// Kill the query process
    fn kill(&mut self) -> Result<(), String> {
        self.process
            .kill()
            .map_err(|e| format!("Failed to kill query process: {}", e))
    }
}

// ============================================================================
// App State
// ============================================================================

pub struct AppState {
    pub query_session: Mutex<Option<QuerySession>>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            query_session: Mutex::new(None),
        }
    }
}

// ============================================================================
// Commands - Health & Version
// ============================================================================

#[tauri::command]
async fn health_check(app: tauri::AppHandle) -> Result<CommandResult, String> {
    use tauri_plugin_shell::ShellExt;

    let sidecar = app
        .shell()
        .sidecar("archifiltre")
        .map_err(|e| format!("Failed to create sidecar: {}", e))?
        .args(["health", "--verbose"]);

    let output = sidecar
        .output()
        .await
        .map_err(|e| format!("Failed to execute health check: {}", e))?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    Ok(CommandResult {
        success: output.status.success(),
        output: stdout,
        error: if stderr.is_empty() {
            None
        } else {
            Some(stderr)
        },
    })
}

#[tauri::command]
async fn get_version(app: tauri::AppHandle) -> Result<CommandResult, String> {
    use tauri_plugin_shell::ShellExt;

    let sidecar = app
        .shell()
        .sidecar("archifiltre")
        .map_err(|e| format!("Failed to create sidecar: {}", e))?
        .args(["version"]);

    let output = sidecar
        .output()
        .await
        .map_err(|e| format!("Failed to get version: {}", e))?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    Ok(CommandResult {
        success: output.status.success(),
        output: stdout,
        error: if stderr.is_empty() {
            None
        } else {
            Some(stderr)
        },
    })
}

// ============================================================================
// Commands - Scan
// ============================================================================

#[tauri::command]
async fn scan_directory(
    app: tauri::AppHandle,
    options: ScanOptions,
) -> Result<CommandResult, String> {
    use tauri_plugin_shell::process::CommandEvent;
    use tauri_plugin_shell::ShellExt;

    let scan_id = options.scan_id.clone();

    // Build CLI arguments
    let mut args = vec![
        "scan".to_string(),
        options.path.clone(),
        "--db".to_string(),
        options.db_name.clone(),
    ];

    if options.include_hidden {
        args.push("--include-hidden".to_string());
    }
    args.push("--batch-size".to_string());
    args.push(options.batch_size.to_string());
    if options.disable_archives {
        args.push("--disable-archives".to_string());
    }

    let sidecar = app
        .shell()
        .sidecar("archifiltre")
        .map_err(|e| format!("Failed to create sidecar: {}", e))?
        .args(&args);

    let (mut rx, _child) = sidecar
        .spawn()
        .map_err(|e| format!("Failed to spawn scan process: {}", e))?;

    let mut full_output = String::new();
    let mut error_output = String::new();
    let mut exit_success = false;

    while let Some(event) = rx.recv().await {
        match event {
            CommandEvent::Stdout(line) => {
                let line_str = String::from_utf8_lossy(&line).to_string();
                full_output.push_str(&line_str);
                full_output.push('\n');
                let _ = app.emit(
                    "scan-progress",
                    ScanProgressEvent {
                        scan_id: scan_id.clone(),
                        line: line_str,
                    },
                );
            }
            CommandEvent::Stderr(line) => {
                let line_str = String::from_utf8_lossy(&line).to_string();
                error_output.push_str(&line_str);
                error_output.push('\n');
                let _ = app.emit(
                    "scan-error",
                    ScanErrorEvent {
                        scan_id: scan_id.clone(),
                        line: line_str,
                    },
                );
            }
            CommandEvent::Terminated(status) => {
                exit_success = status.code == Some(0);
                let _ = app.emit(
                    "scan-complete",
                    ScanCompleteEvent {
                        scan_id: scan_id.clone(),
                        success: exit_success,
                    },
                );
                break;
            }
            _ => {}
        }
    }

    Ok(CommandResult {
        success: exit_success,
        output: full_output,
        error: if exit_success {
            None
        } else {
            Some(error_output)
        },
    })
}

// ============================================================================
// Commands - Checksum
// ============================================================================

#[tauri::command]
async fn compute_checksums(
    app: tauri::AppHandle,
    options: ChecksumOptions,
) -> Result<CommandResult, String> {
    use tauri_plugin_shell::process::CommandEvent;
    use tauri_plugin_shell::ShellExt;

    let mut args = vec![
        "checksum".to_string(),
        "--algorithm".to_string(),
        options.algorithm.clone(),
    ];
    if options.each_file {
        args.push("--each-file".to_string());
    }

    let sidecar = app
        .shell()
        .sidecar("archifiltre")
        .map_err(|e| format!("Failed to create sidecar: {}", e))?
        .args(&args);

    let (mut rx, _child) = sidecar
        .spawn()
        .map_err(|e| format!("Failed to spawn checksum process: {}", e))?;

    let mut full_output = String::new();
    let mut error_output = String::new();

    while let Some(event) = rx.recv().await {
        match event {
            CommandEvent::Stdout(line) => {
                let line_str = String::from_utf8_lossy(&line);
                full_output.push_str(&line_str);
                full_output.push('\n');
                let _ = app.emit("checksum-progress", &line_str.to_string());
            }
            CommandEvent::Stderr(line) => {
                let line_str = String::from_utf8_lossy(&line);
                error_output.push_str(&line_str);
                error_output.push('\n');
                let _ = app.emit("checksum-error", &line_str.to_string());
            }
            CommandEvent::Terminated(status) => {
                let _ = app.emit("checksum-complete", status.code == Some(0));
                break;
            }
            _ => {}
        }
    }

    Ok(CommandResult {
        success: error_output.is_empty(),
        output: full_output,
        error: if error_output.is_empty() {
            None
        } else {
            Some(error_output)
        },
    })
}

// ============================================================================
// Commands - Export
// ============================================================================

#[tauri::command]
async fn export_csv(
    app: tauri::AppHandle,
    options: ExportOptions,
) -> Result<CommandResult, String> {
    use std::io::{BufRead, BufReader};
    use std::process::Command;
    use tauri::Manager;

    let mut args = vec!["export".to_string(), options.output_path.clone()];
    if options.full_paths {
        args.push("--full-paths".to_string());
    }
    if let Some(ref db) = options.db_name {
        args.push("--db".to_string());
        args.push(db.clone());
    }

    // Get the sidecar path (same logic as query session)
    let resource_dir = app
        .path()
        .resource_dir()
        .map_err(|e| format!("Failed to get resource dir: {}", e))?;

    let possible_names: Vec<&str> = if cfg!(target_os = "windows") {
        vec!["archifiltre-x86_64-pc-windows-msvc.exe", "archifiltre.exe"]
    } else if cfg!(target_os = "macos") {
        #[cfg(target_arch = "aarch64")]
        let names = vec!["archifiltre-aarch64-apple-darwin", "archifiltre"];
        #[cfg(target_arch = "x86_64")]
        let names = vec!["archifiltre-x86_64-apple-darwin", "archifiltre"];
        #[cfg(not(any(target_arch = "aarch64", target_arch = "x86_64")))]
        let names = vec!["archifiltre-x86_64-apple-darwin", "archifiltre"];
        names
    } else {
        vec!["archifiltre-x86_64-unknown-linux-gnu", "archifiltre"]
    };

    let mut sidecar_path = None;
    for name in &possible_names {
        let path = resource_dir.join(name);
        if path.exists() {
            sidecar_path = Some(path);
            break;
        }
    }

    // Fallback: check next to the executable itself (portable installs)
    if sidecar_path.is_none() {
        let exe_dir = std::env::current_exe()
            .ok()
            .and_then(|p| p.parent().map(|p| p.to_path_buf()));
        if let Some(ref dir) = exe_dir {
            for name in &possible_names {
                let path = dir.join(name);
                if path.exists() {
                    sidecar_path = Some(path);
                    break;
                }
            }
        }
    }

    let binary_path = sidecar_path.ok_or_else(|| {
        format!("Sidecar binary not found. Looked in: {:?}", resource_dir)
    })?;

    // Spawn the process
    let mut child = Command::new(&binary_path)
        .args(&args)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to spawn export process: {}", e))?;

    let stdout = child.stdout.take().ok_or("Failed to get stdout")?;
    let stderr = child.stderr.take().ok_or("Failed to get stderr")?;

    let mut full_output = String::new();
    let mut error_output = String::new();

    // Read stdout
    let stdout_reader = BufReader::new(stdout);
    for line in stdout_reader.lines() {
        if let Ok(line_str) = line {
            full_output.push_str(&line_str);
            full_output.push('\n');
            let _ = app.emit("export-progress", &line_str);
        }
    }

    // Read stderr
    let stderr_reader = BufReader::new(stderr);
    for line in stderr_reader.lines() {
        if let Ok(line_str) = line {
            error_output.push_str(&line_str);
            error_output.push('\n');
            let _ = app.emit("export-error", &line_str);
        }
    }

    // Wait for the process to finish
    let status = child
        .wait()
        .map_err(|e| format!("Failed to wait for process: {}", e))?;
    let _ = app.emit("export-complete", status.success());

    Ok(CommandResult {
        success: error_output.is_empty() && status.success(),
        output: full_output,
        error: if error_output.is_empty() {
            None
        } else {
            Some(error_output)
        },
    })
}

// ============================================================================
// Commands - Query Session
// ============================================================================

#[tauri::command]
async fn start_query_session(
    app: tauri::AppHandle,
    state: tauri::State<'_, Arc<AppState>>,
    db_name: Option<String>,
) -> Result<String, String> {
    use std::process::Command;
    use tauri::Manager;

    let mut session_guard = state.query_session.lock().await;

    // Kill existing session if any
    if let Some(mut existing) = session_guard.take() {
        let _ = existing.kill();
    }

    // Build args
    let mut args = vec!["query".to_string()];
    if let Some(ref db) = db_name {
        args.push("--db".to_string());
        args.push(db.clone());
    }

    // Get the sidecar path from Tauri's resource directory
    // The sidecar is bundled as "archifiltre" in the externalBin config
    let resource_dir = app
        .path()
        .resource_dir()
        .map_err(|e| format!("Failed to get resource dir: {}", e))?;

    // Try different possible sidecar locations (simple naming convention)
    let possible_names: Vec<&str> = if cfg!(target_os = "windows") {
        vec!["archifiltre-x86_64-pc-windows-msvc.exe", "archifiltre.exe"]
    } else if cfg!(target_os = "macos") {
        #[cfg(target_arch = "aarch64")]
        let names = vec!["archifiltre-aarch64-apple-darwin", "archifiltre"];
        #[cfg(target_arch = "x86_64")]
        let names = vec!["archifiltre-x86_64-apple-darwin", "archifiltre"];
        #[cfg(not(any(target_arch = "aarch64", target_arch = "x86_64")))]
        let names = vec!["archifiltre-x86_64-apple-darwin", "archifiltre"];
        names
    } else {
        vec!["archifiltre-x86_64-unknown-linux-gnu", "archifiltre"]
    };

    let mut sidecar_path = None;
    for name in &possible_names {
        let path = resource_dir.join(name);
        if path.exists() {
            sidecar_path = Some(path);
            break;
        }
    }

    // Fallback: check next to the executable itself (portable installs)
    if sidecar_path.is_none() {
        let exe_dir = std::env::current_exe()
            .ok()
            .and_then(|p| p.parent().map(|p| p.to_path_buf()));
        if let Some(ref dir) = exe_dir {
            for name in &possible_names {
                let path = dir.join(name);
                if path.exists() {
                    sidecar_path = Some(path);
                    break;
                }
            }
        }
    }

    let binary_path = sidecar_path.ok_or_else(|| {
        format!("Sidecar binary not found. Looked in: {:?}", resource_dir)
    })?;

    // Spawn the process with piped stdin/stdout
    let mut process = Command::new(&binary_path)
        .args(&args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to spawn query process: {}", e))?;

    let stdin = process.stdin.take().ok_or("Failed to get stdin")?;

    let stdout = process.stdout.take().ok_or("Failed to get stdout")?;

    let stdout_reader = BufReader::new(stdout);

    // Create session (run_id will be set after reading __ready__ message)
    let mut session = QuerySession {
        process,
        stdin,
        stdout: stdout_reader,
        run_id: String::new(),
    };

    // Read the ready message from the query process
    // Format: { "id": "__ready__", "ok": true, "data": { "run_id": "...", "status": "ready" } }
    let mut ready_line = String::new();
    session
        .stdout
        .read_line(&mut ready_line)
        .map_err(|e| format!("Failed to read ready message: {}", e))?;

    if ready_line.is_empty() {
        let _ = session.kill();
        return Err("Query process closed before sending ready message".to_string());
    }

    // Parse the ready message as QueryResponse
    let ready_response: QueryResponse = serde_json::from_str(&ready_line).map_err(|e| {
        format!(
            "Failed to parse ready message: {} - raw: {}",
            e,
            ready_line.trim()
        )
    })?;

    if !ready_response.ok {
        let _ = session.kill();
        return Err(ready_response
            .error
            .unwrap_or_else(|| "Unknown error starting query session".to_string()));
    }

    // Extract run_id from the ready response data
    let run_id = ready_response
        .data
        .as_ref()
        .and_then(|d| d.get("run_id"))
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    session.run_id = run_id.clone();

    *session_guard = Some(session);

    Ok(run_id)
}

#[tauri::command]
async fn stop_query_session(state: tauri::State<'_, Arc<AppState>>) -> Result<(), String> {
    let mut session_guard = state.query_session.lock().await;
    if let Some(mut session) = session_guard.take() {
        session.kill()?;
    }
    Ok(())
}

#[tauri::command]
async fn send_query(
    state: tauri::State<'_, Arc<AppState>>,
    request: QueryRequest,
) -> Result<QueryResponse, String> {
    let mut session_guard = state.query_session.lock().await;
    let session = session_guard.as_mut().ok_or("No active query session")?;

    session.query(&request)
}

#[tauri::command]
async fn is_query_session_active(state: tauri::State<'_, Arc<AppState>>) -> Result<bool, String> {
    let session_guard = state.query_session.lock().await;
    Ok(session_guard.is_some())
}

#[tauri::command]
async fn get_query_run_id(state: tauri::State<'_, Arc<AppState>>) -> Result<String, String> {
    let session_guard = state.query_session.lock().await;
    let session = session_guard.as_ref().ok_or("No active query session")?;
    Ok(session.run_id.clone())
}

// ============================================================================
// Commands - Path Validation
// ============================================================================

#[tauri::command]
async fn validate_path(path: String) -> Result<PathValidationResult, String> {
    use std::fs;
    use std::path::Path;

    let path_obj = Path::new(&path);

    // Check if path exists
    let exists = path_obj.exists();
    if !exists {
        return Ok(PathValidationResult {
            valid: false,
            is_directory: false,
            readable: false,
            exists: false,
            error: Some("Path does not exist".to_string()),
        });
    }

    // Check if it's a directory
    let is_directory = path_obj.is_dir();
    if !is_directory {
        return Ok(PathValidationResult {
            valid: false,
            is_directory: false,
            readable: true,
            exists: true,
            error: Some("Path is not a directory".to_string()),
        });
    }

    // Check if readable by attempting to read directory contents
    let readable = fs::read_dir(path_obj).is_ok();
    if !readable {
        return Ok(PathValidationResult {
            valid: false,
            is_directory: true,
            readable: false,
            exists: true,
            error: Some("Directory is not readable".to_string()),
        });
    }

    Ok(PathValidationResult {
        valid: true,
        is_directory: true,
        readable: true,
        exists: true,
        error: None,
    })
}

// ============================================================================
// Commands - Window Management
// ============================================================================

/// Create a new window
#[tauri::command]
async fn create_window(app: tauri::AppHandle) -> Result<String, String> {
    use tauri::{WebviewUrl, WebviewWindowBuilder};

    // Generate a unique label for the new window
    let window_id = format!("main-{}", uuid::Uuid::new_v4());

    // Create the new window with the same settings as the main window
    let _window = WebviewWindowBuilder::new(&app, &window_id, WebviewUrl::App("index.html".into()))
        .title("Archifiltre")
        .inner_size(1200.0, 800.0)
        .min_inner_size(900.0, 600.0)
        .resizable(true)
        .center()
        .decorations(false)
        .transparent(true)
        .shadow(true)
        .build()
        .map_err(|e| format!("Failed to create window: {}", e))?;

    Ok(window_id)
}

// ============================================================================
// Main
// ============================================================================

fn main() {
    let app_state = Arc::new(AppState::default());

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_os::init())
        .manage(app_state)
        .invoke_handler(tauri::generate_handler![
            // Health & Version
            health_check,
            get_version,
            // Scan
            scan_directory,
            // Checksum
            compute_checksums,
            // Export
            export_csv,
            // Query Session
            start_query_session,
            stop_query_session,
            send_query,
            is_query_session_active,
            get_query_run_id,
            // Path Validation
            validate_path,
            // Window Management
            create_window,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
