/**
 * Tauri API Wrapper
 * Provides typed functions to interact with the Tauri backend commands.
 *
 * Phase 1: Updated for multi-tab support with scan_id routing
 */

import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { open as openDialog } from '@tauri-apps/plugin-dialog';

// ================================
// Basic Types
// ================================

export interface CommandResult {
	success: boolean;
	output: string;
	error: string | null;
}

export interface ScanOptions {
	/** Unique identifier for this scan (generated by frontend) */
	scanId: string;
	/** Job identifier for the unified job protocol */
	jobId?: string;
	/** Database name for storing scan results (e.g., "tab-{uuid}") */
	dbName: string;
	/** Path to scan */
	path: string;
	includeHidden?: boolean;
	batchSize?: number;
	disableArchives?: boolean;
}

export interface PathValidationResult {
	valid: boolean;
	isDirectory: boolean;
	readable: boolean;
	exists: boolean;
	error?: string;
}

// ================================
// Event Payload Types (with scan_id for routing)
// ================================

export interface ScanProgressEvent {
	scanId: string;
	line: string;
}

export interface ScanErrorEvent {
	scanId: string;
	line: string;
}

export interface ScanCompleteEvent {
	scanId: string;
	success: boolean;
}

// ================================
// Callback Types
// ================================

export type ScanProgressCallback = (event: ScanProgressEvent) => void;
export type ScanErrorCallback = (event: ScanErrorEvent) => void;
export type ScanCompleteCallback = (event: ScanCompleteEvent) => void;

// Legacy callback types (for backwards compatibility during migration)
export type ProgressCallback = (line: string) => void;
export type CompleteCallback = (success: boolean) => void;

// ================================
// Dialog Functions
// ================================

/**
 * Open a folder selection dialog.
 * Returns the selected folder path or null if cancelled.
 */
export async function selectFolder(): Promise<string | null> {
	const result = await openDialog({
		directory: true,
		multiple: false,
		title: 'Select a folder to analyze'
	});
	if (typeof result === 'string') {
		return result;
	}
	return null;
}

// ================================
// Path Validation
// ================================

/**
 * Validate a file system path.
 * Checks if the path exists, is a directory, and is readable.
 */
export async function validatePath(path: string): Promise<PathValidationResult> {
	try {
		return await invoke<PathValidationResult>('validate_path', { path });
	} catch (error) {
		return {
			valid: false,
			isDirectory: false,
			readable: false,
			exists: false,
			error: `Validation failed: ${error}`
		};
	}
}

// ================================
// Command Functions - Health & Version
// ================================

/**
 * Check if the CLI binary is healthy and accessible.
 */
export async function healthCheck(): Promise<CommandResult> {
	return await invoke<CommandResult>('health_check');
}

/**
 * Get the CLI version string.
 */
export async function getVersion(): Promise<CommandResult> {
	return await invoke<CommandResult>('get_version');
}

// ================================
// Command Functions - Scan
// ================================

/**
 * Start scanning a directory.
 * This is an async operation - progress is reported via events.
 *
 * @param options - Scan options including scanId for event routing
 */
export async function scanDirectory(options: ScanOptions): Promise<CommandResult> {
	return await invoke<CommandResult>('scan_directory', { options });
}

// ================================
// Event Listeners - Scan (with scan_id routing)
// ================================

/**
 * Listen for scan progress updates (stdout from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanProgress(callback: ScanProgressCallback): Promise<UnlistenFn> {
	return await listen<ScanProgressEvent>('scan-progress', (event) => callback(event.payload));
}

/**
 * Listen for scan errors (stderr from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanError(callback: ScanErrorCallback): Promise<UnlistenFn> {
	return await listen<ScanErrorEvent>('scan-error', (event) => callback(event.payload));
}

/**
 * Listen for scan completion.
 * Events include scanId for routing to the correct tab.
 */
export async function onScanComplete(callback: ScanCompleteCallback): Promise<UnlistenFn> {
	return await listen<ScanCompleteEvent>('scan-complete', (event) => callback(event.payload));
}

// ================================
// Job Protocol Events
// ================================

export interface JobUpdateEvent {
	jobId: string;
	/** Raw JSON JobEvent line from the sidecar stdout */
	line: string;
}

export type JobUpdateCallback = (event: JobUpdateEvent) => void;

/**
 * Listen for unified job updates from any pipeline command.
 * Each event carries the job ID and the raw JSON line to parse.
 */
export async function onJobUpdate(callback: JobUpdateCallback): Promise<UnlistenFn> {
	return await listen<JobUpdateEvent>('job-update', (event) => callback(event.payload));
}

/**
 * Pause a running job.
 */
export async function pauseJob(jobId: string): Promise<void> {
	await invoke('pause_job', { jobId });
}

/**
 * Resume a paused job.
 */
export async function resumeJob(jobId: string): Promise<void> {
	await invoke('resume_job', { jobId });
}

/**
 * Cancel a running or paused job.
 */
export async function cancelJob(jobId: string): Promise<void> {
	await invoke('cancel_job', { jobId });
}

// ================================
// Query Session Types
// ================================

export interface QueryRequest {
	id: string;
	action: string;
	[key: string]: unknown;
}

export interface QueryResponse {
	id: string;
	ok: boolean;
	data?: unknown;
	error?: string;
}

// ================================
// Tree Types (matching query command output)
// ================================

/** Enrichment flags joined onto every node for the visualization. */
export interface NodeEnrichment {
	/** Display-name override, or null. */
	alias: string | null;
	has_comment: boolean;
	has_tag: boolean;
	/** This element or any ancestor directory is marked for deletion (cascade). */
	tagged_for_deletion: boolean;
}

/** Directory node from get_tree query - flat structure */
export interface DirectoryNode extends NodeEnrichment {
	path: string;
	name: string;
	depth: number;
	total_size: number;
	file_count: number;
	dir_count: number;
}

/** Tree data from get_tree query */
export interface TreeData {
	root: string | null;
	directories: DirectoryNode[];
}

/** Stats data from get_stats query */
export interface ScanStats {
	totalFiles: number;
	totalPhysicalSize: number;
	totalContentSize: number;
	duplicateGroups: number;
	duplicateFiles: number;
	totalArchives: number;
	totalArchiveEntries: number;
	archiveFormats: string[];
}

/** File node from get_files query */
export interface FileNode extends NodeEnrichment {
	path: string;
	name: string;
	size: number;
	content_size: number | null;
	mtime: number;
	is_directory: boolean;
	is_hidden: boolean;
	hash: string | null;
	is_archive: boolean;
	archive_format: string | null;
}

/** Files data from get_files query */
export interface FilesData {
	files: FileNode[];
	total: number;
	has_more: boolean;
	cursor: string | null;
}

// ================================
// Command Functions - Query Session
// ================================

/**
 * Start a query session for interactive database access.
 * @param dbName - Optional database name (defaults to 'main')
 * @returns The run_id for the current scan in that database
 */
export async function startQuerySession(dbName?: string): Promise<string> {
	return await invoke<string>('start_query_session', { dbName });
}

/**
 * Stop the current query session.
 */
export async function stopQuerySession(): Promise<void> {
	await invoke('stop_query_session');
}

/**
 * Send a query to the active session.
 */
export async function sendQuery(request: QueryRequest): Promise<QueryResponse> {
	return await invoke<QueryResponse>('send_query', { request });
}

/**
 * Check if a query session is currently active.
 */
export async function isQuerySessionActive(): Promise<boolean> {
	return await invoke<boolean>('is_query_session_active');
}

/**
 * Get the run_id from the active query session.
 */
export async function getQueryRunId(): Promise<string> {
	return await invoke<string>('get_query_run_id');
}

// ================================
// Query Helper Functions
// ================================

/**
 * Query the file tree structure for visualization.
 * Returns a flat list of directories that can be built into a hierarchy.
 * Requires an active query session.
 */
export async function queryTree(): Promise<TreeData | null> {
	const response = await sendQuery({
		id: `get_tree_${Date.now()}`,
		action: 'get_tree'
	});

	if (!response.ok) {
		console.error('Failed to get tree:', response.error);
		return null;
	}

	return response.data as TreeData;
}

/**
 * Query scan statistics.
 * Requires an active query session.
 */
export async function queryStats(): Promise<ScanStats | null> {
	const response = await sendQuery({
		id: `get_stats_${Date.now()}`,
		action: 'get_stats'
	});

	if (!response.ok) {
		console.error('Failed to get stats:', response.error);
		return null;
	}

	return response.data as ScanStats;
}

/**
 * Ping the query session to check if it's alive.
 */
export async function pingQuerySession(): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `ping_${Date.now()}`,
			action: 'ping'
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Query files in a specific directory.
 * Use empty string for root directory.
 * Requires an active query session.
 */
export async function queryFiles(
	dirPath: string = '',
	limit: number = 1000
): Promise<FilesData | null> {
	const response = await sendQuery({
		id: `get_files_${Date.now()}`,
		action: 'get_files',
		path: dirPath,
		limit
	});

	if (!response.ok) {
		console.error('Failed to get files:', response.error);
		return null;
	}

	return response.data as FilesData;
}

/** AI-generated directory description */
export interface DirectoryDescription {
	description: string | null;
	model?: string;
	cached?: boolean;
	error?: string;
}

/**
 * Get an AI-generated description of a directory.
 * Uses an LLM API to analyze the directory tree structure.
 * Results are cached in the database.
 * Requires an active query session.
 */
export async function queryDirectoryDescription(
	dirPath: string = ''
): Promise<DirectoryDescription | null> {
	try {
		const response = await sendQuery({
			id: `describe_directory_${Date.now()}`,
			action: 'describe_directory',
			path: dirPath
		});

		if (!response.ok) {
			console.error('Failed to get directory description:', response.error);
			return { description: null, error: response.error };
		}

		return response.data as DirectoryDescription;
	} catch (error) {
		console.error('Error querying directory description:', error);
		return null;
	}
}

/** Date statistics for all descendant files of a directory */
export interface DirDateStats {
	min: number | null;
	max: number | null;
	median: number | null;
	count: number;
}

/**
 * Get min, max, and median mtime across all descendant files of a directory.
 * Requires an active query session.
 */
export async function queryDirDateStats(dirPath: string): Promise<DirDateStats | null> {
	const response = await sendQuery({
		id: `get_dir_date_stats_${Date.now()}`,
		action: 'get_dir_date_stats',
		path: dirPath
	});

	if (!response.ok) {
		console.error('Failed to get dir date stats:', response.error);
		return null;
	}

	return response.data as DirDateStats;
}

export interface CompositionEntry {
	ext: string | null;
	count: number;
	size: number;
}

/**
 * File-type composition (bytes + count grouped by extension) of a subtree.
 * Requires an active query session. Pass '' for the whole scan.
 */
export async function queryComposition(dirPath: string): Promise<CompositionEntry[] | null> {
	const response = await sendQuery({
		id: `get_composition_${Date.now()}`,
		action: 'get_composition',
		path: dirPath
	});

	if (!response.ok) {
		console.error('Failed to get composition:', response.error);
		return null;
	}

	return response.data as CompositionEntry[];
}

// ================================
// Thumbnail Cache Types & Helpers
// ================================

/** Cached thumbnail result from the database */
export interface CachedThumbnail {
	thumbnail: string | null;
	width?: number;
	height?: number;
	format?: string;
	cached: boolean;
}

/**
 * Check if a thumbnail is cached in the database.
 * Returns the base64-encoded thumbnail if cached, or null if not.
 * Requires an active query session.
 */
export async function getThumbnailFromCache(filePath: string): Promise<CachedThumbnail | null> {
	try {
		const response = await sendQuery({
			id: `get_thumbnail_${Date.now()}`,
			action: 'get_thumbnail',
			path: filePath
		});

		if (!response.ok) {
			return null;
		}

		return response.data as CachedThumbnail;
	} catch {
		return null;
	}
}

/**
 * Store a generated thumbnail in the database cache.
 * Requires an active query session.
 */
export async function storeThumbnailInCache(
	filePath: string,
	thumbnailBase64: string,
	width: number,
	height: number,
	format: string
): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `store_thumbnail_${Date.now()}`,
			action: 'store_thumbnail',
			path: filePath,
			thumbnail: thumbnailBase64,
			width,
			height,
			format
		});

		return response.ok;
	} catch {
		return false;
	}
}

// ================================
// Delete Tags Functions
// ================================

/** Delete tag entry returned by the backend */
export interface DeleteTag {
	path: string;
	created_at: number;
}

/** Result from get_delete_tags query */
export interface GetDeleteTagsResult {
	tags: DeleteTag[];
}

/**
 * Mark a file or directory for deletion.
 * Requires an active query session.
 */
export async function setDeleteTag(path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_delete_tag_${Date.now()}`,
			action: 'set_delete_tag',
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Remove the deletion tag from a file or directory.
 * Requires an active query session.
 */
export async function removeDeleteTag(path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `remove_delete_tag_${Date.now()}`,
			action: 'remove_delete_tag',
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Get all deletion tags for the current scan.
 * Requires an active query session.
 */
export async function getDeleteTags(): Promise<GetDeleteTagsResult | null> {
	try {
		const response = await sendQuery({
			id: `get_delete_tags_${Date.now()}`,
			action: 'get_delete_tags'
		});

		if (!response.ok) {
			console.error('Failed to get delete tags:', response.error);
			return null;
		}

		return response.data as GetDeleteTagsResult;
	} catch {
		return null;
	}
}

// ================================
// Enrichment Functions
// ================================
//
// Aliases, comments and tags. PGlite is the single source of truth: these
// wrappers write through to the DB, and reads come either from get_enrichment
// (one-shot hydration of the tag dictionary on scan load) or from
// getElementEnrichment (query-on-select for the details panel). Per-element
// enrichment is never cached in a long-lived store.

/** A tag in the run's dictionary */
export interface Tag {
	tag_id: string;
	name: string;
}

/** Full enrichment snapshot for a run (hydration) */
export interface EnrichmentData {
	aliases: { path: string; alias: string }[];
	comments: { path: string; comment: string }[];
	tags: Tag[];
	assignments: { tag_id: string; path: string }[];
	deleteTags: { path: string; created_at: number }[];
}

/** Enrichment for a single selected element */
export interface ElementEnrichment {
	alias: string | null;
	comment: string | null;
	tagIds: string[];
	directlyTaggedForDeletion: boolean;
	ancestorTaggedForDeletion: boolean;
	/** Aliases for this element and its ancestors, keyed by path (breadcrumb display). */
	pathAliases: Record<string, string>;
}

/** Set or clear an element's alias. Empty/equal-to-name clears it (backend). */
export async function setAlias(path: string, alias: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_alias_${Date.now()}`,
			action: 'set_alias',
			path,
			alias
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Set or clear an element's comment. Empty clears it (backend). */
export async function setComment(path: string, comment: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_comment_${Date.now()}`,
			action: 'set_comment',
			path,
			comment
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Create a new tag; resolves to the generated tag, or null on failure. */
export async function createTag(name: string): Promise<Tag | null> {
	try {
		const response = await sendQuery({
			id: `create_tag_${Date.now()}`,
			action: 'create_tag',
			name
		});
		return response.ok ? (response.data as Tag) : null;
	} catch {
		return null;
	}
}

/** Rename a tag in the dictionary. */
export async function renameTag(tagId: string, name: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `rename_tag_${Date.now()}`,
			action: 'rename_tag',
			tag_id: tagId,
			name
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Delete a tag from the dictionary; cascades to its assignments. */
export async function deleteTag(tagId: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `delete_tag_${Date.now()}`,
			action: 'delete_tag',
			tag_id: tagId
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Assign an existing tag to an element. */
export async function assignTag(tagId: string, path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `assign_tag_${Date.now()}`,
			action: 'assign_tag',
			tag_id: tagId,
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Remove a tag from an element. */
export async function unassignTag(tagId: string, path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `unassign_tag_${Date.now()}`,
			action: 'unassign_tag',
			tag_id: tagId,
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Fetch the full enrichment snapshot for the current scan (hydration). */
export async function getEnrichment(): Promise<EnrichmentData | null> {
	try {
		const response = await sendQuery({
			id: `get_enrichment_${Date.now()}`,
			action: 'get_enrichment'
		});
		if (!response.ok) {
			console.error('Failed to get enrichment:', response.error);
			return null;
		}
		return response.data as EnrichmentData;
	} catch {
		return null;
	}
}

/** Fetch enrichment for a single element (query-on-select). */
export async function getElementEnrichment(path: string): Promise<ElementEnrichment | null> {
	try {
		const response = await sendQuery({
			id: `get_element_enrichment_${Date.now()}`,
			action: 'get_element_enrichment',
			path
		});
		return response.ok ? (response.data as ElementEnrichment) : null;
	} catch {
		return null;
	}
}

// ================================
// Export Functions
// ================================

export interface ExportOptions {
	outputPath: string;
	jobId?: string;
	fullPaths?: boolean;
	dbName?: string;
	deletionOnly?: boolean;
}

/**
 * Export scan results to CSV file.
 * @param options - Export options including output path and database name
 */
export async function exportCsv(options: ExportOptions): Promise<CommandResult> {
	return await invoke<CommandResult>('export_csv', { options });
}

/**
 * Open a save file dialog for CSV export.
 * Returns the selected file path or null if cancelled.
 */
export async function selectExportPath(type: string = 'export'): Promise<string | null> {
	const { save } = await import('@tauri-apps/plugin-dialog');
	const result = await save({
		title: 'Export scan results',
		defaultPath: `archifiltre-${type}-${Date.now()}.csv`,
		filters: [{ name: 'CSV', extensions: ['csv'] }]
	});
	return result;
}

// ================================
// Tree Hierarchy Helpers
// ================================

/**
 * Build a map of parent path -> children for tree navigation.
 */
export function buildTreeHierarchy(directories: DirectoryNode[]): Map<string, DirectoryNode[]> {
	const childrenMap = new Map<string, DirectoryNode[]>();

	for (const dir of directories) {
		const parentPath = dir.path.includes('/')
			? dir.path.substring(0, dir.path.lastIndexOf('/'))
			: '';

		if (!childrenMap.has(parentPath)) {
			childrenMap.set(parentPath, []);
		}
		childrenMap.get(parentPath)!.push(dir);
	}

	// Sort children by size (largest first)
	for (const children of childrenMap.values()) {
		children.sort((a, b) => b.total_size - a.total_size);
	}

	return childrenMap;
}

/**
 * Get children of a directory path.
 */
export function getChildren(
	path: string,
	childrenMap: Map<string, DirectoryNode[]>
): DirectoryNode[] {
	return childrenMap.get(path) ?? [];
}

/**
 * Get root directories (those at minimum depth).
 */
export function getRootDirectories(directories: DirectoryNode[]): DirectoryNode[] {
	if (directories.length === 0) return [];
	const minDepth = Math.min(...directories.map((d) => d.depth));
	return directories
		.filter((d) => d.depth === minDepth)
		.sort((a, b) => b.total_size - a.total_size);
}

/**
 * Generate a color for a directory path.
 */
export function getColorForPath(path: string, isDirectory: boolean): string {
	if (!isDirectory) return '#6b7280'; // gray for files

	// Hash the path to get a consistent color
	let hash = 0;
	for (let i = 0; i < path.length; i++) {
		hash = path.charCodeAt(i) + ((hash << 5) - hash);
	}

	// Use HSL for better color distribution
	const hue = Math.abs(hash) % 360;
	const saturation = 65 + (Math.abs(hash >> 8) % 20); // 65-85%
	const lightness = 45 + (Math.abs(hash >> 16) % 15); // 45-60%

	return `hsl(${hue}, ${saturation}%, ${lightness}%)`;
}

// ================================
// Command Functions - Window Management
// ================================

/**
 * Create a new application window.
 * Each window is independent and manages its own tabs.
 * @returns The window ID of the newly created window
 */
export async function createWindow(): Promise<string> {
	return await invoke<string>('create_window');
}

// ================================
// Utility Functions
// ================================

/**
 * Format bytes into a human-readable string.
 */
export function formatBytes(bytes: number): string {
	if (bytes === 0) return '0 B';
	const units = ['B', 'KB', 'MB', 'GB', 'TB'];
	const k = 1024;
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return `${(bytes / Math.pow(k, i)).toFixed(i > 0 ? 1 : 0)} ${units[i]}`;
}

/**
 * Format a number with locale-specific thousand separators.
 */
export function formatNumber(num: number): string {
	return num.toLocaleString();
}

/**
 * Generate a unique identifier for scans/tabs.
 * Uses crypto.randomUUID() which is available in all modern browsers.
 */
export function generateId(): string {
	return crypto.randomUUID();
}
