/**
 * Tauri API Wrapper
 * Provides typed functions to interact with the Tauri backend commands.
 *
 * Phase 1: Updated for multi-tab support with scan_id routing
 */

import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { open as openDialog } from '@tauri-apps/plugin-dialog';

// ================================
// Basic Types
// ================================

export interface CommandResult {
	success: boolean;
	output: string;
	error: string | null;
}

export interface ScanOptions {
	/** Unique identifier for this scan (generated by frontend) */
	scanId: string;
	/** Database name for storing scan results (e.g., "tab-{uuid}") */
	dbName: string;
	/** Path to scan */
	path: string;
	includeHidden?: boolean;
	batchSize?: number;
	disableArchives?: boolean;
}

export interface PathValidationResult {
	valid: boolean;
	isDirectory: boolean;
	readable: boolean;
	exists: boolean;
	error?: string;
}

// ================================
// Event Payload Types (with scan_id for routing)
// ================================

export interface ScanProgressEvent {
	scanId: string;
	line: string;
}

export interface ScanErrorEvent {
	scanId: string;
	line: string;
}

export interface ScanCompleteEvent {
	scanId: string;
	success: boolean;
}

// ================================
// Callback Types
// ================================

export type ScanProgressCallback = (event: ScanProgressEvent) => void;
export type ScanErrorCallback = (event: ScanErrorEvent) => void;
export type ScanCompleteCallback = (event: ScanCompleteEvent) => void;

// Legacy callback types (for backwards compatibility during migration)
export type ProgressCallback = (line: string) => void;
export type CompleteCallback = (success: boolean) => void;

// ================================
// Dialog Functions
// ================================

/**
 * Open a folder selection dialog.
 * Returns the selected folder path or null if cancelled.
 */
export async function selectFolder(): Promise<string | null> {
	const result = await openDialog({
		directory: true,
		multiple: false,
		title: 'Select a folder to analyze'
	});
	if (typeof result === 'string') {
		return result;
	}
	return null;
}

// ================================
// Path Validation
// ================================

/**
 * Validate a file system path.
 * Checks if the path exists, is a directory, and is readable.
 */
export async function validatePath(path: string): Promise<PathValidationResult> {
	try {
		return await invoke<PathValidationResult>('validate_path', { path });
	} catch (error) {
		return {
			valid: false,
			isDirectory: false,
			readable: false,
			exists: false,
			error: `Validation failed: ${error}`
		};
	}
}

// ================================
// Command Functions - Health & Version
// ================================

/**
 * Check if the CLI binary is healthy and accessible.
 */
export async function healthCheck(): Promise<CommandResult> {
	return await invoke<CommandResult>('health_check');
}

/**
 * Get the CLI version string.
 */
export async function getVersion(): Promise<CommandResult> {
	return await invoke<CommandResult>('get_version');
}

// ================================
// Command Functions - Scan
// ================================

/**
 * Start scanning a directory.
 * This is an async operation - progress is reported via events.
 *
 * @param options - Scan options including scanId for event routing
 */
export async function scanDirectory(options: ScanOptions): Promise<CommandResult> {
	return await invoke<CommandResult>('scan_directory', { options });
}

// ================================
// Event Listeners - Scan (with scan_id routing)
// ================================

/**
 * Listen for scan progress updates (stdout from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanProgress(callback: ScanProgressCallback): Promise<UnlistenFn> {
	return await listen<ScanProgressEvent>('scan-progress', (event) => callback(event.payload));
}

/**
 * Listen for scan errors (stderr from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanError(callback: ScanErrorCallback): Promise<UnlistenFn> {
	return await listen<ScanErrorEvent>('scan-error', (event) => callback(event.payload));
}

/**
 * Listen for scan completion.
 * Events include scanId for routing to the correct tab.
 */
export async function onScanComplete(callback: ScanCompleteCallback): Promise<UnlistenFn> {
	return await listen<ScanCompleteEvent>('scan-complete', (event) => callback(event.payload));
}

// ================================
// Query Session Types
// ================================

export interface QueryRequest {
	id: string;
	action: string;
	[key: string]: unknown;
}

export interface QueryResponse {
	id: string;
	ok: boolean;
	data?: unknown;
	error?: string;
}

// ================================
// Command Functions - Query Session
// ================================

/**
 * Start a query session for interactive database access.
 * @param dbName - Optional database name (defaults to 'main')
 * @returns The run_id for the current scan in that database
 */
export async function startQuerySession(dbName?: string): Promise<string> {
	return await invoke<string>('start_query_session', { dbName });
}

/**
 * Stop the current query session.
 */
export async function stopQuerySession(): Promise<void> {
	await invoke('stop_query_session');
}

/**
 * Send a query to the active session.
 */
export async function sendQuery(request: QueryRequest): Promise<QueryResponse> {
	return await invoke<QueryResponse>('send_query', { request });
}

/**
 * Check if a query session is currently active.
 */
export async function isQuerySessionActive(): Promise<boolean> {
	return await invoke<boolean>('is_query_session_active');
}

/**
 * Get the run_id from the active query session.
 */
export async function getQueryRunId(): Promise<string> {
	return await invoke<string>('get_query_run_id');
}

// ================================
// Command Functions - Window Management
// ================================

/**
 * Create a new application window.
 * Each window is independent and manages its own tabs.
 * @returns The window ID of the newly created window
 */
export async function createWindow(): Promise<string> {
	return await invoke<string>('create_window');
}

// ================================
// Utility Functions
// ================================

/**
 * Format bytes into a human-readable string.
 */
export function formatBytes(bytes: number): string {
	if (bytes === 0) return '0 B';
	const units = ['B', 'KB', 'MB', 'GB', 'TB'];
	const k = 1024;
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return `${(bytes / Math.pow(k, i)).toFixed(i > 0 ? 1 : 0)} ${units[i]}`;
}

/**
 * Format a number with locale-specific thousand separators.
 */
export function formatNumber(num: number): string {
	return num.toLocaleString();
}

/**
 * Generate a unique identifier for scans/tabs.
 * Uses crypto.randomUUID() which is available in all modern browsers.
 */
export function generateId(): string {
	return crypto.randomUUID();
}
