/**
 * Tauri API Wrapper
 * Provides typed functions to interact with the Tauri backend commands.
 *
 * Phase 1: Updated for multi-tab support with scan_id routing
 */

import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
export type { UnlistenFn };
import { open as openDialog } from '@tauri-apps/plugin-dialog';
import { logFrontend } from '$lib/log-buffer';
import { circuitBreaker, handleAll, ConsecutiveBreaker, isBrokenCircuitError } from 'cockatiel';

// ================================
// Single-owner DB mode (read-while-scanning)
// ================================
// When enabled, the data layer routes through the Rust Owner (one process owning
// the PGlite connection: scan writes + live reads), instead of the legacy two
// sidecars. Runtime switch via localStorage so it can be flipped without a rebuild.
// Owner mode is now the DEFAULT (live read-while-scanning, full-depth tree,
// concurrent scans). The legacy two-sidecar path is on its way out — kept behind
// an escape hatch (`archifiltre-owner-db = '0'`) only until owner mode is confirmed
// in the real Tauri app, then both the flag and the legacy path get deleted.
export function useOwnerDb(): boolean {
	try {
		return typeof localStorage === 'undefined' || localStorage.getItem('archifiltre-owner-db') !== '0';
	} catch {
		return true;
	}
}

let _ownerReqCounter = 0;
const ownerReqId = (): string => `q${Date.now().toString(36)}_${_ownerReqCounter++}`;

// ================================
// Basic Types
// ================================

export interface CommandResult {
	success: boolean;
	output: string;
	error: string | null;
}

export interface ScanOptions {
	/** Unique identifier for this scan (generated by frontend) */
	scanId: string;
	/** Job identifier for the unified job protocol */
	jobId?: string;
	/** Database name for storing scan results (e.g., "tab-{uuid}") */
	dbName: string;
	/** Path to scan */
	path: string;
	includeHidden?: boolean;
	batchSize?: number;
	disableArchives?: boolean;
}

export interface PathValidationResult {
	valid: boolean;
	isDirectory: boolean;
	readable: boolean;
	exists: boolean;
	error?: string;
}

// ================================
// Event Payload Types (with scan_id for routing)
// ================================

export interface ScanProgressEvent {
	scanId: string;
	line: string;
}

export interface ScanErrorEvent {
	scanId: string;
	line: string;
}

export interface ScanCompleteEvent {
	scanId: string;
	success: boolean;
}

// ================================
// Callback Types
// ================================

export type ScanProgressCallback = (event: ScanProgressEvent) => void;
export type ScanErrorCallback = (event: ScanErrorEvent) => void;
export type ScanCompleteCallback = (event: ScanCompleteEvent) => void;

// Legacy callback types (for backwards compatibility during migration)
export type ProgressCallback = (line: string) => void;
export type CompleteCallback = (success: boolean) => void;

// ================================
// Dialog Functions
// ================================

/**
 * Open a folder selection dialog.
 * Returns the selected folder path or null if cancelled.
 */
export async function selectFolder(): Promise<string | null> {
	const result = await openDialog({
		directory: true,
		multiple: false,
		title: 'Select a folder to analyze'
	});
	if (typeof result === 'string') {
		return result;
	}
	return null;
}

// ================================
// Path Validation
// ================================

/**
 * Validate a file system path.
 * Checks if the path exists, is a directory, and is readable.
 */
export async function validatePath(path: string): Promise<PathValidationResult> {
	try {
		return await invoke<PathValidationResult>('validate_path', { path });
	} catch (error) {
		return {
			valid: false,
			isDirectory: false,
			readable: false,
			exists: false,
			error: `Validation failed: ${error}`
		};
	}
}

// ================================
// Command Functions - Health & Version
// ================================

/**
 * Check if the CLI binary is healthy and accessible.
 */
export async function healthCheck(): Promise<CommandResult> {
	return await invoke<CommandResult>('health_check');
}

/**
 * Get the CLI version string.
 */
export async function getVersion(): Promise<CommandResult> {
	return await invoke<CommandResult>('get_version');
}

/** Durable status of a scan's datadir, read from its meta sidecar (no PGlite open). */
export interface DatadirMeta {
	version: number;
	dbName: string;
	runId: string | null;
	rootPath: string | null;
	status: 'running' | 'paused' | 'complete' | 'cancelled';
	fileCount: number | null;
	updatedAt: number;
}

export interface DatadirEntry {
	dbName: string;
	meta: DatadirMeta | null;
	hasSnapshot: boolean;
}

/**
 * List the scan datadirs on disk with their durable meta — the on-disk truth the app
 * reconciles against its localStorage scan list at startup. Empty array on any failure
 * (reconciliation is best-effort; it must never block app launch).
 */
export async function listDatadirs(): Promise<DatadirEntry[]> {
	try {
		const res = await invoke<CommandResult>('list_datadirs');
		if (!res.success || !res.output) return [];
		const parsed = JSON.parse(res.output) as { datadirs?: DatadirEntry[] };
		return parsed.datadirs ?? [];
	} catch {
		return [];
	}
}

// ================================
// Command Functions - Scan
// ================================

/**
 * Start scanning a directory.
 * This is an async operation - progress is reported via events.
 *
 * @param options - Scan options including scanId for event routing
 */
export async function scanDirectory(options: ScanOptions): Promise<CommandResult> {
	if (!useOwnerDb()) {
		return await invoke<CommandResult>('scan_directory', { options });
	}
	// Owner mode: one owner PROCESS per db. Ensure THIS db's owner is up (other dbs'
	// owners keep running → concurrent scans), point queries at it, fire the scan (acks
	// immediately, streams job:progress/resource events), and resolve on job:complete /
	// job:error — same canonical vocabulary as the scan command.
	// The ONE place allowed to bring a scan database into existence — a scan is starting, so a
	// datadir is exactly what's wanted. Everywhere else attaches to one that already exists.
	await ensureSession(options.dbName, true); // seed the gate: the scan IS this db's owner
	setActiveQueryDb(options.dbName);
	const jobId = options.jobId || options.scanId;
	const done = new Promise<CommandResult>((resolve) => {
		let unlisten: UnlistenFn | null = null;
		void onJobUpdate((e) => {
			if (e.jobId !== jobId) return;
			let m: { event?: string; error?: string };
			try {
				m = JSON.parse(e.line);
			} catch {
				return;
			}
			if (m.event === 'job:complete') {
				unlisten?.();
				resolve({ success: true, output: '', error: null });
			} else if (m.event === 'job:error') {
				unlisten?.();
				resolve({ success: false, output: '', error: m.error ?? 'scan failed' });
			}
		}).then((u) => {
			unlisten = u;
		});
	});
	await invoke('session_request', {
		dbName: options.dbName,
		request: {
			id: ownerReqId(),
			action: 'start_scan',
			path: options.path,
			jobId,
			batchSize: options.batchSize,
			includeHidden: options.includeHidden,
			enableArchives: !options.disableArchives,
		},
	});
	return done;
}

// ================================
// Event Listeners - Scan (with scan_id routing)
// ================================

/**
 * Listen for scan progress updates (stdout from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanProgress(callback: ScanProgressCallback): Promise<UnlistenFn> {
	return await listen<ScanProgressEvent>('scan-progress', (event) => callback(event.payload));
}

/**
 * Listen for scan errors (stderr from CLI).
 * Events include scanId for routing to the correct tab.
 */
export async function onScanError(callback: ScanErrorCallback): Promise<UnlistenFn> {
	return await listen<ScanErrorEvent>('scan-error', (event) => callback(event.payload));
}

/**
 * Listen for scan completion.
 * Events include scanId for routing to the correct tab.
 */
export async function onScanComplete(callback: ScanCompleteCallback): Promise<UnlistenFn> {
	return await listen<ScanCompleteEvent>('scan-complete', (event) => callback(event.payload));
}

// ================================
// Job Protocol Events
// ================================

export interface JobUpdateEvent {
	jobId: string;
	/** Raw JSON JobEvent line from the sidecar stdout */
	line: string;
}

export type JobUpdateCallback = (event: JobUpdateEvent) => void;

/**
 * Listen for unified job updates from any pipeline command.
 * Each event carries the job ID and the raw JSON line to parse.
 */
export async function onJobUpdate(callback: JobUpdateCallback): Promise<UnlistenFn> {
	return await listen<JobUpdateEvent>('job-update', (event) => callback(event.payload));
}

/**
 * Pause a running job.
 */
export async function pauseJob(jobId: string): Promise<void> {
	await invoke('pause_job', { jobId });
}

/**
 * Resume a paused job.
 */
export async function resumeJob(jobId: string): Promise<void> {
	await invoke('resume_job', { jobId });
}

/**
 * Cancel a running or paused job.
 */
export async function cancelJob(jobId: string): Promise<void> {
	await invoke('cancel_job', { jobId });
}

// ================================
// Query Session Types
// ================================

export interface QueryRequest {
	id: string;
	action: string;
	[key: string]: unknown;
}

export interface QueryResponse {
	id: string;
	ok: boolean;
	data?: unknown;
	error?: string;
}

// ================================
// Tree Types (matching query command output)
// ================================

/** Enrichment flags joined onto every node for the visualization. */
export interface NodeEnrichment {
	/** Display-name override, or null. */
	alias: string | null;
	has_comment: boolean;
	has_tag: boolean;
	/** This element or any ancestor directory is marked for deletion (cascade). */
	tagged_for_deletion: boolean;
}

/** Directory node from get_tree query - flat structure */
export interface DirectoryNode extends NodeEnrichment {
	path: string;
	name: string;
	depth: number;
	total_size: number;
	file_count: number;
	dir_count: number;
	/** Levels the deepest descendant sits below this directory (0 = leaf folder).
	 *  Optional: provisional (mid-scan) directories don't carry it yet. */
	max_depth?: number;
	/** Path of that deepest descendant, or null when the folder is empty. */
	deepest_path?: string | null;
	/** This directory node is really an archive container (foo.zip): it drills in like a
	 *  folder, but renders like a compressed file (dark tint + archive icon). */
	is_archive?: boolean;
	archive_format?: string | null;
	/** Descendant mtime range + representative median (epoch seconds). Present only for a
	 *  settled tree (complete/paused); absent during a live scan. Drives date colour + sort
	 *  for folders. */
	min_mtime?: number;
	max_mtime?: number;
	median_mtime?: number;
}

/** Tree data from get_tree query */
export interface TreeData {
	root: string | null;
	directories: DirectoryNode[];
}

/** Stats data from get_stats query */
export interface ScanStats {
	totalFiles: number;
	totalFolders: number;
	totalPhysicalSize: number;
	totalContentSize: number;
	duplicateGroups: number;
	duplicateFiles: number;
	totalArchives: number;
	totalArchiveEntries: number;
	archiveFormats: string[];
}

/** File node from get_files query */
export interface FileNode extends NodeEnrichment {
	path: string;
	name: string;
	size: number;
	content_size: number | null;
	mtime: number;
	is_directory: boolean;
	is_hidden: boolean;
	hash: string | null;
	is_archive: boolean;
	archive_format: string | null;
	/** The scan could not fully process this unit (unreadable / too large / too deep / timed
	 *  out / truncated archive) — it carries an extraction_error. Drives the "Not processed"
	 *  list filter. Only set by get_all_files. */
	not_processed?: boolean;
	/** Duplicates mode only: total copies sharing this file's hash across the whole result
	 *  (independent of pagination), so the UI can show the real "N×" for a group even when a
	 *  page boundary splits it. Undefined outside duplicates mode. */
	dup_count?: number;
}

/** Files data from get_files query */
export interface FilesData {
	files: FileNode[];
	total: number;
	has_more: boolean;
	cursor: string | null;
}

// ================================
// Command Functions - Query Session
// ================================

// Owner mode runs one owner PROCESS per db (concurrent scans/tabs/windows), so every
// query must say WHICH db/owner it targets. This tracks the db of the scan currently
// being viewed/scanned; it's set whenever a session is (re)established for a db
// (startQuerySession / scanDirectory), i.e. on scan start and on switching to a tab.
let activeQueryDb: string | undefined;

/** Owner mode: point subsequent queries at this db's owner. */
export function setActiveQueryDb(dbName: string | undefined): void {
	activeQueryDb = dbName;
}

// ── Session-readiness gate (ONE ordering point for every consumer) ──
// The owner session is a shared prerequisite for every DB read (queryTree, describe_prepare,
// hover stats, …). It's created by scanDirectory (during a scan) or startQuerySession (on
// reopen/pause) — and consumers used to fire independently of whoever created it, so one could
// hit the owner registry before it was registered → "No active session for this db" (e.g. a
// reopened scan's root summary racing startQuerySession). Every consumer funnels through
// sendQuery, so we gate THERE: sendQuery awaits ensureSession(db). start_session is idempotent
// on the Rust side (holds the owners lock, reuses a live owner, respawns a dead one), so this
// memoized promise is purely an await-point + de-dup — it can never open a second opener.
const TRANSIENT_SESSION_ERROR =
	/session closed before responding|session not alive|No active session|request timed out|session did not respond/i;

/** True for the recoverable owner-handoff errors: the owner isn't up yet / just died / is
 *  respawning. These must be retried (or awaited), never surfaced as a terminal failure. */
export function isTransientSessionError(e: unknown): boolean {
	return TRANSIENT_SESSION_ERROR.test(String((e as { message?: unknown })?.message ?? e));
}

const sessionReady = new Map<string, Promise<string>>();

/** Ensure this db's owner is up (or coming up) and resolve once it's ready. Idempotent:
 *  concurrent callers share ONE start_session — whoever asks first triggers it, the rest await
 *  the same promise, so no consumer can run before the owner is registered. Owner-mode only. */
export function ensureSession(dbName?: string, allowCreate = false): Promise<string> {
	const db = dbName ?? activeQueryDb ?? 'main';
	let p = sessionReady.get(db);
	if (!p) {
		// `allowCreate` defaults to FALSE: attaching to a scan is routine, bringing one into
		// existence is not. Most queries omit a dbName and inherit `activeQueryDb`, so with
		// creation on by default an app-level question (model_status, ping) aimed at an empty
		// tab quietly built a whole empty database for it — invisible to reconciliation, and
		// never reclaimed. Only scanDirectory, which genuinely starts a scan, passes true.
		p = invoke<string>('start_session', { dbName: db, allowCreate }).catch((e) => {
			sessionReady.delete(db); // failed to establish → let a later call retry cleanly
			throw e;
		});
		sessionReady.set(db, p);
	}
	return p;
}

/** Forget a db's session (owner died / stopped / db deleted) so the next consumer re-establishes it. */
export function invalidateSession(dbName?: string): void {
	const db = dbName ?? activeQueryDb;
	if (db) sessionReady.delete(db);
}

/**
 * Start a query session for interactive database access.
 * @param dbName - Optional database name (defaults to 'main')
 * @returns The run_id for the current scan in that database
 */
export async function startQuerySession(dbName?: string): Promise<string> {
	if (useOwnerDb()) {
		activeQueryDb = dbName;
		// Go through the gate so this shares the SAME start_session as any consumer (e.g. the
		// describe engine) that raced ahead — one owner, one promise, no double-establish.
		return await ensureSession(dbName);
	}
	return await invoke<string>('start_query_session', { dbName });
}

/**
 * Stop the current query session.
 */
export async function stopQuerySession(): Promise<void> {
	if (useOwnerDb()) {
		invalidateSession(activeQueryDb); // owner is going away → next consumer re-establishes
		await invoke('stop_session', { dbName: activeQueryDb });
		return;
	}
	await invoke('stop_query_session');
}

/**
 * Send a query to a session. Owner mode runs one process per db, so pass `dbName`
 * to target a specific db's owner explicitly — REQUIRED whenever two scans/tabs are
 * live, because the shared `activeQueryDb` pointer is only correct for the active tab
 * and a query carrying the wrong db reads the other owner (e.g. unmaterialized data
 * mid-scan → empty tree). Omitting it falls back to the active tab's pointer.
 */
export async function sendQuery(
	request: QueryRequest,
	dbName?: string,
	timeoutMs?: number
): Promise<QueryResponse> {
	// Guarantee a UNIQUE wire id. Callers build ids as `${action}_${Date.now()}`, which
	// collides when two of the same request fire in the same millisecond — e.g. get_tree is
	// double-fired at scan completion (once from the job:complete handler, once from the
	// activeScan subscription). A duplicate id makes the owner's pending-map insert overwrite
	// and DROP the first request's response channel, surfacing as "session closed before
	// responding" (owner.rs). A process-monotonic suffix makes every id collision-proof while
	// keeping the readable action prefix. Correlation is internal (callers await the response,
	// not the id), so rewriting the id here is safe.
	const uniqueRequest = { ...request, id: `${request.id}_${_ownerReqCounter++}` };
	if (useOwnerDb()) {
		const db = dbName ?? activeQueryDb;
		// THE GATE: never touch the owner before it's registered. This is what removes the
		// reopen/pause "No active session for this db" race for EVERY consumer at once — the
		// describe engine no longer needs special handling, its describe_prepare simply waits.
		await ensureSession(db);
		const fire = (req: QueryRequest) =>
			invoke<QueryResponse>('session_request', {
				dbName: db,
				request: req,
				// The owner replies to some requests only after a long job (e.g. a model
				// download finishes). Callers pass a generous timeout so those don't hit the
				// default 15 s cap and surface as a spurious "session did not respond" error.
				...(timeoutMs != null ? { timeoutMs } : {})
			});
		try {
			return await fire(uniqueRequest);
		} catch (e) {
			// Owner died between ensure and use (crash / respawn) → re-establish once and retry
			// with a fresh id. A single retry, never a loop: a second failure propagates.
			if (isTransientSessionError(e)) {
				invalidateSession(db);
				await ensureSession(db);
				return await fire({ ...request, id: `${request.id}_${_ownerReqCounter++}` });
			}
			throw e;
		}
	}
	return await invoke<QueryResponse>('send_query', { request: uniqueRequest });
}

// ── Scan control (owner mode) ──────────────────────────────────────────────
// Routed through the session control channel (session_request), so a paused scan's
// owner keeps all committed data and resume re-walks only the un-enumerated remainder.
// `job:paused` streams back via onJobUpdate. NOTE: distinct from the legacy
// pauseJob/resumeJob/cancelJob above, which drive the old CLI job-control signals.

/** Pause the running scan on this db's owner (soft-stop; fully resumable). */
export async function pauseScan(dbName: string): Promise<void> {
	if (!useOwnerDb()) return;
	await sendQuery({ id: `pause_${Date.now()}`, action: 'pause_scan' }, dbName);
}

/** Resume a paused/interrupted scan on this db's owner (re-runs with resume:true). */
export async function resumeScan(dbName: string): Promise<void> {
	if (!useOwnerDb()) return;
	await sendQuery({ id: `resume_${Date.now()}`, action: 'resume_scan' }, dbName);
}

/** Stop the scan on this db's owner, persisted as cancelled — same mechanism as pause
 *  (data kept, resumable); only the persisted status differs. */
export async function cancelScan(dbName: string): Promise<void> {
	if (!useOwnerDb()) return;
	await sendQuery({ id: `cancel_${Date.now()}`, action: 'cancel_scan' }, dbName);
}

/** Discard a scan entirely — used when CLOSING a tab.
 *
 *  The owner tombstones the datadir and acks within ~50 ms, then removes the files in the
 *  background and exits on its own. So this resolves fast and, crucially, REPORTS whether the
 *  scan is actually gone: a false success here is what used to make a tab disappear from a scan
 *  that was still on disk and came back at the next launch.
 *
 *  Deliberately does NOT stop_session afterwards. The owner exits itself once the removal is
 *  done; killing it here raced the removal it had just been asked to perform. */
export async function deleteDatabase(dbName: string): Promise<boolean> {
	if (!useOwnerDb()) return true;
	let deleted = false;
	try {
		// Ensure an owner exists for this db BEFORE asking it to delete itself — deleting a scan
		// we never opened this session would otherwise have no process to ask.
		await ensureSession(dbName);
		const res = await sendQuery({ id: `delete_${Date.now()}`, action: 'delete_db' }, dbName);
		deleted = res.ok === true;
	} catch (e) {
		// The owner acks then exits, so a late "session closed" AFTER a successful ack is normal.
		// Any other failure means the scan may still be on disk — say so.
		deleted = isTransientSessionError(e) && deleted;
	}
	invalidateSession(dbName); // owner is exiting → forget it so a re-scan re-establishes cleanly
	return deleted;
}

// ── Undo / redo (per-scan enrichment history) ──────────────────────────────
export interface UndoRedoState {
	ok?: boolean; // whether an op was actually applied
	summary?: string; // human description of the undone/redone op
	canUndo: boolean;
	canRedo: boolean;
}

/** Undo the last enrichment op on this scan's db. Returns the new can-undo/redo + summary. */
export async function undo(dbName?: string): Promise<UndoRedoState | null> {
	const res = await sendQuery({ id: `undo_${Date.now()}`, action: 'undo' }, dbName);
	return res.ok ? (res.data as UndoRedoState) : null;
}

/** Redo the next enrichment op on this scan's db. */
export async function redo(dbName?: string): Promise<UndoRedoState | null> {
	const res = await sendQuery({ id: `redo_${Date.now()}`, action: 'redo' }, dbName);
	return res.ok ? (res.data as UndoRedoState) : null;
}

/** Cheap can-undo / can-redo for enabling the controls. */
export async function getUndoState(dbName?: string): Promise<{ canUndo: boolean; canRedo: boolean } | null> {
	const res = await sendQuery({ id: `ustate_${Date.now()}`, action: 'undo_state' }, dbName);
	return res.ok ? (res.data as { canUndo: boolean; canRedo: boolean }) : null;
}

/** Does a durable annotation snapshot exist for this scan's root (offer restore)? */
export async function hasAnnotationBackup(
	dbName?: string
): Promise<{ hasBackup: boolean; count: number }> {
	const res = await sendQuery(
		{ id: `hasbackup_${Date.now()}`, action: 'has_annotation_backup' },
		dbName
	);
	return res.ok ? (res.data as { hasBackup: boolean; count: number }) : { hasBackup: false, count: 0 };
}

/** Restore the durable annotation snapshot onto this (re-scanned) run. Returns how many
 *  annotations were re-applied and which paths no longer exist (orphaned). */
export async function restoreAnnotations(
	dbName?: string
): Promise<{ restored: number; orphaned: string[] }> {
	const res = await sendQuery(
		{ id: `restore_${Date.now()}`, action: 'restore_annotations' },
		dbName
	);
	return res.ok ? (res.data as { restored: number; orphaned: string[] }) : { restored: 0, orphaned: [] };
}

/** Export this scan's annotations to a JSON file (portable backup / move between machines). */
export async function exportAnnotations(
	outputPath: string,
	dbName?: string
): Promise<{ count: number; path: string }> {
	const res = await sendQuery(
		{ id: `expann_${Date.now()}`, action: 'export_annotations', outputPath },
		dbName
	);
	if (!res.ok) throw new Error(res.error ?? 'Export failed');
	return res.data as { count: number; path: string };
}

/** Import annotations from a JSON file onto this scan (path-keyed restore). */
export async function importAnnotations(
	inputPath: string,
	dbName?: string
): Promise<{ restored: number; orphaned: string[] }> {
	const res = await sendQuery(
		{ id: `impann_${Date.now()}`, action: 'import_annotations', inputPath },
		dbName
	);
	if (!res.ok) throw new Error(res.error ?? 'Import failed');
	return res.data as { restored: number; orphaned: string[] };
}

/**
 * Check if a query session is currently active.
 */
export async function isQuerySessionActive(): Promise<boolean> {
	if (useOwnerDb()) return await invoke<boolean>('is_session_active', { dbName: activeQueryDb });
	return await invoke<boolean>('is_query_session_active');
}

/**
 * Get the run_id from the active query session.
 */
export async function getQueryRunId(): Promise<string> {
	return await invoke<string>('get_query_run_id');
}

// ================================
// Query Helper Functions
// ================================

/**
 * Query the file tree structure for visualization.
 * Returns a flat list of directories that can be built into a hierarchy.
 * Requires an active query session.
 */
export async function queryTree(dbName?: string): Promise<TreeData | null> {
	const response = await sendQuery({
		id: `get_tree_${Date.now()}`,
		action: 'get_tree'
	}, dbName);

	if (!response.ok) {
		console.error('Failed to get tree:', response.error);
		return null;
	}

	return response.data as TreeData;
}

/**
 * Query scan statistics.
 * Requires an active query session.
 */
export async function queryStats(dbName?: string): Promise<ScanStats | null> {
	const response = await sendQuery({
		id: `get_stats_${Date.now()}`,
		action: 'get_stats'
	}, dbName);

	if (!response.ok) {
		console.error('Failed to get stats:', response.error);
		return null;
	}

	return response.data as ScanStats;
}

/**
 * Ping the query session to check if it's alive.
 */
export async function pingQuerySession(): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `ping_${Date.now()}`,
			action: 'ping'
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Query files in a specific directory.
 * Use empty string for root directory.
 * Requires an active query session.
 */
export async function queryFiles(
	dirPath: string = '',
	limit: number = 1000
): Promise<FilesData | null> {
	const response = await sendQuery({
		id: `get_files_${Date.now()}`,
		action: 'get_files',
		path: dirPath,
		limit
	});

	if (!response.ok) {
		console.error('Failed to get files:', response.error);
		return null;
	}

	return response.data as FilesData;
}

/** All files in the scan (recursive), server-sorted + paginated — backs the Flat list.
 *  One windowed query instead of walking every directory in JS. */
export async function queryAllFiles(
	sortBy: 'name' | 'size' | 'mtime' = 'size',
	sortDir: 'asc' | 'desc' = 'desc',
	limit: number = 500,
	offset: number = 0,
	duplicatesOnly: boolean = false
): Promise<{ files: FileNode[]; total: number; has_more: boolean } | null> {
	const response = await sendQuery({
		id: `get_all_files_${Date.now()}`,
		action: 'get_all_files',
		sort_by: sortBy,
		sort_dir: sortDir,
		limit,
		offset,
		duplicates_only: duplicatesOnly
	});

	if (!response.ok) {
		console.error('Failed to get all files:', response.error);
		return null;
	}

	return response.data as { files: FileNode[]; total: number; has_more: boolean };
}

/** AI-generated directory description */
export interface DirectoryDescription {
	description: string | null;
	model?: string;
	cached?: boolean;
	error?: string;
	/** Mid-scan only: the summary was built from the on-disk fallback (walker hadn't inserted
	 *  children yet), so it is provisional and should be regenerated from the full tree at
	 *  completion. Absent/false → authoritative: the engine keeps it and just persists it. */
	provisional?: boolean;
}

/**
 * Get an AI-generated description of a directory.
 * Uses an LLM API to analyze the directory tree structure.
 * Results are cached in the database.
 * Requires an active query session.
 */
/** Active UI language ('en' | 'fr' | 'de'), mirroring i18n's resolveLocale without importing it. */
export function currentUiLang(): string {
	const supported = ['en', 'fr', 'de'];
	try {
		const pref = localStorage.getItem('archifiltre-locale');
		const raw = pref && pref !== 'system' ? pref : (navigator.language || 'en');
		const l = raw.slice(0, 2).toLowerCase();
		return supported.includes(l) ? l : 'en';
	} catch {
		return 'en';
	}
}

// ── App-global LLM host (ONE Rust-owned llm-helper; one warm model for every scan + Settings) ──

interface LlmEnvelope {
	ok: boolean;
	data?: Record<string, unknown>;
	error?: string;
}

/**
 * One request to THE app-global LLM host. Throws ONLY on transport failure (host unspawnable /
 * non-Tauri env like the Chromium bridge) — business failures come back as `{ok:false, error}`.
 * Callers use the throw to fall back to the legacy in-owner path, keeping CLI/bridge working.
 */
async function llmRequest(req: Record<string, unknown>): Promise<LlmEnvelope> {
	return (await invoke('llm_request', { req })) as LlmEnvelope;
}

/** Shared circuit breaker for the LLM host generate call: after consecutive failures it opens and
 *  describes fast-fail instead of flooding a down host, then half-opens to recover. Counts thrown
 *  failures only (a `{ok:false}` result is handled by the caller). */
const llmHostBreaker = circuitBreaker(handleAll, {
	halfOpenAfter: 30_000,
	breaker: new ConsecutiveBreaker(5)
});
llmHostBreaker.onBreak(() => logFrontend('llm.circuit.open', { cooldownMs: 30_000 }));
llmHostBreaker.onHalfOpen(() => logFrontend('llm.circuit.half-open'));
llmHostBreaker.onReset(() => logFrontend('llm.circuit.reset'));

/**
 * Best-effort: drain the LLM helper's in-memory RFC5424 log ring (backend/model-load + the
 * AI-stage trace) for the export bundle. This is the copy NOT held in the open .log file, so it
 * survives a Windows lock. Never throws / never blocks the export: no host, no helper, or any
 * error → returns undefined and the export omits it. Analog of the owner's fetchSidecarRing().
 */
export async function fetchHelperRing(): Promise<string | undefined> {
	try {
		const env = await llmRequest({ type: 'get_ring_log' });
		const ring = env.ok ? (env.data as { ring?: unknown })?.ring : undefined;
		return typeof ring === 'string' && ring.length > 0 ? ring : undefined;
	} catch {
		return undefined; // non-Tauri env or host unspawnable → just omit it
	}
}

/** Options for a describe: who asked (user click vs auto rule — autos are preemptible on
 *  the host), a stable clientId for cancellation/queue-tracking, and an explicit db so the
 *  coordinator's requests never retarget when the active tab changes mid-flight. */
export interface DescribeOpts {
	kind?: 'user' | 'auto';
	clientId?: string;
	dbName?: string;
	/** Correlation id for this describe invocation — threaded to owner (prepare/store) + helper
	 *  (generate) so the whole trace shares one id in the exported logs (see llm-describe.ts). */
	describeId?: string;
}

/** Cancel a describe by its clientId — drops it from the host queue, or aborts the running
 *  generation. Fire-and-forget: used when the user clicks another folder, so abandoned
 *  generations no longer hog the engine. */
export function cancelDescribe(clientId: string): void {
	void llmRequest({ type: 'cancel', clientId }).catch(() => {});
}

/**
 * Persist an already-generated summary for future cache hits WITHOUT regenerating it — the
 * "promote" path. The engine calls this at scan completion for an authoritative mid-scan
 * summary (built from the full tree, so no need to regenerate): it was left uncached while
 * scanning, and this stamps it into the DB so re-opening the scan is instant. Fire-and-forget;
 * a failed cache write must never disturb the on-screen summary.
 */
export function persistDescription(
	dirPath: string,
	description: string,
	model: string,
	dbName?: string
): void {
	void sendQuery(
		{
			id: `store_description_${Date.now()}`,
			action: 'store_description',
			path: dirPath,
			description,
			model,
			lang: currentUiLang()
		},
		dbName
	).catch(() => {});
}

export async function queryDirectoryDescription(
	dirPath: string = '',
	onToken?: (delta: string) => void,
	opts?: DescribeOpts
): Promise<DirectoryDescription | null> {
	let unlistenTokens: UnlistenFn | null = null;
	try {
		// LLM provider from Settings › LLM. `off` → don't call. `local` → on-device Qwen in the
		// app-global llm-helper. `external` → the configured OpenAI-compatible endpoint.
		// Default (no value) is `local`.
		let mode = 'local';
		try {
			const m = localStorage.getItem('archifiltre-ai-mode');
			if (m) mode = m;
		} catch {
			/* no localStorage → default (local) */
		}
		if (mode === 'off') return { description: null, error: 'LLM disabled' };

		// Summarize in the user's UI language (resolves 'system' → OS locale → en).
		const lang = currentUiLang();

		// A per-request id so streamed token events reach only this call (survives folder
		// switches — tokens for an abandoned stream simply don't match).
		const streamId = onToken ? `desc_${Date.now()}_${_ownerReqCounter}` : undefined;

		// Provider params for the backend AI API. local = the on-device model; external = the
		// configured OpenAI-compatible endpoint (creds from Settings, else the sidecar's env).
		let llm: {
			provider: 'local' | 'external';
			model?: string;
			lang?: string;
			baseUrl?: string;
			apiKey?: string;
		};
		if (mode === 'external') {
			llm = { provider: 'external', lang };
			try {
				const raw = localStorage.getItem('archifiltre-llm-config');
				if (raw) {
					const c = JSON.parse(raw);
					if (c && (c.baseUrl || c.apiKey || c.model)) llm = { provider: 'external', lang, ...c };
				}
			} catch {
				/* no/bad config → the sidecar falls back to its LLM_* env vars */
			}
		} else {
			let model = 'qwen2.5-0.5b'; // GPU-safe default (1.5B on a laptop GPU can freeze the desktop)
			try {
				const m = localStorage.getItem('archifiltre-local-model');
				if (m) model = m;
			} catch {
				/* default model */
			}
			llm = { provider: 'local', model, lang };
		}

		// Subscribe to streamed token events for this request (cache hits emit none). Tokens reach
		// us as `describe:token` matched by streamId, whichever provider served the describe.
		if (streamId && onToken) {
			unlistenTokens = await onJobUpdate((e) => {
				try {
					const msg = JSON.parse(e.line);
					if (msg.event === 'describe:token' && msg.streamId === streamId && msg.delta)
						onToken(msg.delta as string);
				} catch {
					/* not our event */
				}
			});
		}

		// One call: the owner orchestrates prepare → infer → store and streams throughout, wrapped in
		// the host breaker so repeated transport failures fast-fail.
		//
		// The timeout is only a backstop against a wedged owner — the backend enforces the real
		// no-progress bound, so time spent merely queued must not count as a failure here. A dead
		// owner still fails fast, since the Rust reader drains pending on exit.
		const timeoutMs = mode === 'local' ? 1_800_000 : 300_000;
		let response;
		try {
			response = await llmHostBreaker.execute(() =>
				sendQuery(
					{
						id: `describe_${Date.now()}`,
						action: 'describe',
						path: dirPath,
						llm,
						...(streamId ? { streamId } : {}),
						...(opts?.clientId ? { clientId: opts.clientId } : {}),
						...(opts?.describeId ? { describeId: opts.describeId } : {})
					},
					opts?.dbName,
					timeoutMs
				)
			);
		} catch (e) {
			if (isBrokenCircuitError(e)) {
				logFrontend('llm.describe.circuit-open', { describeId: opts?.describeId });
				return { description: null, error: 'AI temporarily unavailable' };
			}
			throw e;
		}

		if (!response.ok) {
			console.error('Failed to get directory description:', response.error);
			return { description: null, error: response.error };
		}

		return response.data as DirectoryDescription;
	} catch (error) {
		console.error('Error querying directory description:', error);
		// Never a silent null: the panel must always have SOMETHING to render (status principle).
		return {
			description: null,
			error: String((error as Error)?.message ?? error) || 'AI runtime not available'
		};
	} finally {
		try {
			await Promise.resolve(unlistenTokens?.()).catch(() => {});
		} catch {
			/* ignore */
		}
	}
}

/** A local model the sidecar can run, and whether it's already on disk. */
export interface LocalModelStatus {
	id: string;
	label: string;
	family: string;
	tier: 'fast' | 'balanced' | 'best';
	note: string;
	size: number;
	license: string;
	downloaded: boolean;
	/** True for a user-imported .gguf (id `custom:<file>`), false/absent for catalogue models. */
	custom?: boolean;
}

/** Ask which local models exist on disk (for the Settings › LLM picker). Preferred: the
 *  app-global LLM host — works with ZERO scans open (Settings is no longer coupled to a scan
 *  session). Falls back to the legacy per-scan action for the bridge/CLI environments. */
export async function getLocalModelStatus(): Promise<{
	models: LocalModelStatus[];
	default: string;
} | null> {
	try {
		const r = await llmRequest({ type: 'model_status' });
		if (r.ok) return r.data as unknown as { models: LocalModelStatus[]; default: string };
	} catch {
		/* host transport unavailable → legacy below */
	}
	try {
		const response = await sendQuery({ id: `model_status_${Date.now()}`, action: 'model_status' });
		if (!response.ok) return null;
		return response.data as { models: LocalModelStatus[]; default: string };
	} catch (error) {
		console.error('Error querying model status:', error);
		return null;
	}
}

/**
 * Pre-load the model on THE app-global LLM host so the first folder summary is warm (~1 s)
 * instead of a cold ~10 s model load. Fired at app launch (and on model change) when local AI
 * is on — completely decoupled from scans, so it can never contend with a describe or ride a
 * scan session. Best-effort: warming is a pure optimization, never surfaces an error.
 */
export async function warmLocalModel(model: string): Promise<boolean> {
	try {
		const r = await llmRequest({ type: 'load', model });
		return r.ok;
	} catch {
		/* non-Tauri env (bridge) or host unavailable — warming is optional */
		return false;
	}
}

export interface ModelDownloadProgress {
	model: string;
	received: number;
	total: number;
	file: string;
	done?: boolean;
	/** Present only on the terminal failure event: why the download stopped. */
	error?: { category: string; message?: string };
}

/** Outcome of a model download: `ok`, or a machine-legible failure `category` the UI maps to a
 *  localized reason (`tls-cert` / `dns` / `connect-timeout` / `proxy-auth` / `http-status` / `disk`). */
export interface ModelDownloadResult {
	ok: boolean;
	errorCategory?: string;
}

/**
 * Download a local model to `~/.archifiltre/models/`. Progress streams back on the
 * job-update channel as `model:download` events; `onProgress` is invoked for each.
 * Resolves once the sidecar confirms the file is fully on disk.
 *
 * `sizeBytes` (the model's total size) sets a generous request timeout — the sidecar
 * only replies when the whole download finishes, which far exceeds the default 15 s cap.
 */
export async function downloadLocalModel(
	id: string,
	onProgress?: (p: ModelDownloadProgress) => void,
	sizeBytes = 0
): Promise<ModelDownloadResult> {
	// The sidecar emits a terminal `model:download` event carrying `error.category` when a
	// download fails (cert / dns / firewall / proxy / disk). Capture it here so the caller can
	// show *why* instead of a bar silently stuck at 0.
	let errorCategory: string | undefined;
	const unlisten: UnlistenFn = await onJobUpdate((e) => {
		try {
			const msg = JSON.parse(e.line);
			if (msg.event !== 'model:download' || msg.model !== id) return;
			if (msg.error) errorCategory = msg.error.category ?? 'unknown';
			else onProgress?.(msg as ModelDownloadProgress);
		} catch {
			/* not our event */
		}
	});
	// Preferred: THE app-global LLM host — the download belongs to the app, not to a scan, so
	// closing/deleting a scan tab can no longer kill it (and it works with zero scans open).
	// Progress arrives on the same job-update events either way.
	try {
		const r = await llmRequest({ type: 'download_model', model: id });
		return { ok: r.ok, errorCategory: r.ok ? undefined : (errorCategory ?? 'unknown') };
	} catch {
		/* host transport unavailable (bridge/CLI env) → legacy per-scan path below */
	}
	// Budget ~1 MB/s as a very conservative floor, plus a 60 s cushion, min 5 min. (The sidecar's
	// own ~30 s stall watchdog fails a dead connection far sooner than this outer cap.)
	const timeoutMs = Math.max(300_000, Math.ceil(sizeBytes / 1_000_000) * 1000 + 60_000);
	try {
		const response = await sendQuery(
			{ id: `download_model_${Date.now()}`, action: 'download_model', model: id },
			undefined,
			timeoutMs
		);
		return { ok: response.ok, errorCategory: response.ok ? undefined : errorCategory };
	} catch {
		// The action rejected (the sidecar threw). Prefer the categorized reason from the event;
		// fall back to a generic connection category if the request itself timed out.
		return { ok: false, errorCategory: errorCategory ?? 'connect-timeout' };
	} finally {
		// Detaching the listener must never surface as an unhandled rejection.
		try {
			await Promise.resolve(unlisten?.()).catch(() => {});
		} catch {
			/* ignore */
		}
	}
}

/**
 * Import a local `.gguf` file as a custom model. The sidecar validates it's a real GGUF and
 * copies it into `~/.archifiltre/models/`; progress streams on the `model:download` channel
 * (only one import runs at a time, so we surface every event). Host-only (needs a file dialog),
 * so no legacy bridge path. Returns the new `custom:<file>` id on success.
 */
export async function importLocalModel(
	srcPath: string,
	onProgress?: (p: ModelDownloadProgress) => void
): Promise<{ ok: boolean; id?: string; error?: string }> {
	const unlisten: UnlistenFn = await onJobUpdate((e) => {
		try {
			const msg = JSON.parse(e.line);
			if (msg.event !== 'model:download' || msg.error) return;
			onProgress?.(msg as ModelDownloadProgress);
		} catch {
			/* not our event */
		}
	});
	try {
		const r = await llmRequest({ type: 'import_model', path: srcPath });
		if (!r.ok) return { ok: false, error: r.error };
		// The terminal reply carries the copied path; the id is `custom:<basename>`.
		const path = String((r.data?.path as string | undefined) ?? '');
		const base = path.replace(/^.*[\\/]/, '');
		return { ok: true, id: base ? `custom:${base}` : undefined };
	} catch (e) {
		return { ok: false, error: String((e as { message?: unknown })?.message ?? e) };
	} finally {
		try {
			await Promise.resolve(unlisten?.()).catch(() => {});
		} catch {
			/* ignore */
		}
	}
}

/** Delete a model's file(s) from `~/.archifiltre/models/` — works for a downloaded catalogue
 *  model OR a custom import. Host-only; best-effort. */
export async function removeLocalModel(id: string): Promise<boolean> {
	try {
		const r = await llmRequest({ type: 'remove_model', model: id });
		return r.ok;
	} catch {
		return false;
	}
}

/** Date statistics for all descendant files of a directory */
export interface DirDateStats {
	min: number | null;
	max: number | null;
	median: number | null;
	count: number;
	/** Age distribution relative to now: cold > 5 yrs, warm 1–5 yrs, active < 1 yr. */
	buckets?: { cold: number; warm: number; active: number };
	/** Subtree size (bytes on disk) + file/dir counts. Available once ingestion completes —
	 *  i.e. throughout the hashing phase — so the panel can fill these before the whole scan
	 *  finishes. `size` matches the settled tree's total_size (both SUM(physical_size)). */
	size?: number;
	fileCount?: number;
	dirCount?: number;
}

/**
 * Get min, max, and median mtime across all descendant files of a directory.
 * Requires an active query session.
 */
export async function queryDirDateStats(dirPath: string): Promise<DirDateStats | null> {
	const response = await sendQuery({
		id: `get_dir_date_stats_${Date.now()}`,
		action: 'get_dir_date_stats',
		path: dirPath
	});

	if (!response.ok) {
		console.error('Failed to get dir date stats:', response.error);
		return null;
	}

	return response.data as DirDateStats;
}

export interface CompositionEntry {
	ext: string | null;
	count: number;
	size: number;
}

/**
 * File-type composition (bytes + count grouped by extension) of a subtree.
 * Requires an active query session. Pass '' for the whole scan.
 */
export async function queryComposition(dirPath: string): Promise<CompositionEntry[] | null> {
	const response = await sendQuery({
		id: `get_composition_${Date.now()}`,
		action: 'get_composition',
		path: dirPath
	});

	if (!response.ok) {
		console.error('Failed to get composition:', response.error);
		return null;
	}

	return response.data as CompositionEntry[];
}

// ================================
// Thumbnail Cache Types & Helpers
// ================================

/** Cached thumbnail result from the database */
export interface CachedThumbnail {
	thumbnail: string | null;
	width?: number;
	height?: number;
	format?: string;
	cached: boolean;
}

/**
 * Check if a thumbnail is cached in the database.
 * Returns the base64-encoded thumbnail if cached, or null if not.
 * Requires an active query session.
 */
export async function getThumbnailFromCache(filePath: string): Promise<CachedThumbnail | null> {
	try {
		const response = await sendQuery({
			id: `get_thumbnail_${Date.now()}`,
			action: 'get_thumbnail',
			path: filePath
		});

		if (!response.ok) {
			return null;
		}

		return response.data as CachedThumbnail;
	} catch {
		return null;
	}
}

/**
 * Store a generated thumbnail in the database cache.
 * Requires an active query session.
 */
export async function storeThumbnailInCache(
	filePath: string,
	thumbnailBase64: string,
	width: number,
	height: number,
	format: string
): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `store_thumbnail_${Date.now()}`,
			action: 'store_thumbnail',
			path: filePath,
			thumbnail: thumbnailBase64,
			width,
			height,
			format
		});

		return response.ok;
	} catch {
		return false;
	}
}

// ================================
// Delete Tags Functions
// ================================

/** Delete tag entry returned by the backend */
export interface DeleteTag {
	path: string;
	created_at: number;
}

/** Result from get_delete_tags query */
export interface GetDeleteTagsResult {
	tags: DeleteTag[];
}

/**
 * Mark a file or directory for deletion.
 * Requires an active query session.
 */
export async function setDeleteTag(path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_delete_tag_${Date.now()}`,
			action: 'set_delete_tag',
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Remove the deletion tag from a file or directory.
 * Requires an active query session.
 */
export async function removeDeleteTag(path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `remove_delete_tag_${Date.now()}`,
			action: 'remove_delete_tag',
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/**
 * Get all deletion tags for the current scan.
 * Requires an active query session.
 */
export async function getDeleteTags(): Promise<GetDeleteTagsResult | null> {
	try {
		const response = await sendQuery({
			id: `get_delete_tags_${Date.now()}`,
			action: 'get_delete_tags'
		});

		if (!response.ok) {
			console.error('Failed to get delete tags:', response.error);
			return null;
		}

		return response.data as GetDeleteTagsResult;
	} catch {
		return null;
	}
}

// ================================
// Enrichment Functions
// ================================
//
// Aliases, comments and tags. PGlite is the single source of truth: these
// wrappers write through to the DB, and reads come either from get_enrichment
// (one-shot hydration of the tag dictionary on scan load) or from
// getElementEnrichment (query-on-select for the details panel). Per-element
// enrichment is never cached in a long-lived store.

/** A tag in the run's dictionary */
export interface Tag {
	tag_id: string;
	name: string;
}

/** Full enrichment snapshot for a run (hydration) */
export interface EnrichmentData {
	aliases: { path: string; alias: string }[];
	comments: { path: string; comment: string }[];
	tags: Tag[];
	assignments: { tag_id: string; path: string }[];
	deleteTags: { path: string; created_at: number }[];
}

/** Enrichment for a single selected element */
export interface ElementEnrichment {
	alias: string | null;
	comment: string | null;
	tagIds: string[];
	directlyTaggedForDeletion: boolean;
	ancestorTaggedForDeletion: boolean;
	/** Aliases for this element and its ancestors, keyed by path (breadcrumb display). */
	pathAliases: Record<string, string>;
}

/** Set or clear an element's alias. Empty/equal-to-name clears it (backend). */
export async function setAlias(path: string, alias: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_alias_${Date.now()}`,
			action: 'set_alias',
			path,
			alias
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Set or clear an element's comment. Empty clears it (backend). */
export async function setComment(path: string, comment: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `set_comment_${Date.now()}`,
			action: 'set_comment',
			path,
			comment
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Create a new tag; resolves to the generated tag, or null on failure. */
export async function createTag(name: string): Promise<Tag | null> {
	try {
		const response = await sendQuery({
			id: `create_tag_${Date.now()}`,
			action: 'create_tag',
			name
		});
		return response.ok ? (response.data as Tag) : null;
	} catch {
		return null;
	}
}

/** Rename a tag in the dictionary. */
export async function renameTag(tagId: string, name: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `rename_tag_${Date.now()}`,
			action: 'rename_tag',
			tag_id: tagId,
			name
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Delete a tag from the dictionary; cascades to its assignments. */
export async function deleteTag(tagId: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `delete_tag_${Date.now()}`,
			action: 'delete_tag',
			tag_id: tagId
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Assign an existing tag to an element. */
export async function assignTag(tagId: string, path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `assign_tag_${Date.now()}`,
			action: 'assign_tag',
			tag_id: tagId,
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Remove a tag from an element. */
export async function unassignTag(tagId: string, path: string): Promise<boolean> {
	try {
		const response = await sendQuery({
			id: `unassign_tag_${Date.now()}`,
			action: 'unassign_tag',
			tag_id: tagId,
			path
		});
		return response.ok;
	} catch {
		return false;
	}
}

/** Fetch the full enrichment snapshot for the current scan (hydration). */
export async function getEnrichment(dbName?: string): Promise<EnrichmentData | null> {
	try {
		const response = await sendQuery({
			id: `get_enrichment_${Date.now()}`,
			action: 'get_enrichment'
		}, dbName);
		if (!response.ok) {
			console.error('Failed to get enrichment:', response.error);
			return null;
		}
		return response.data as EnrichmentData;
	} catch {
		return null;
	}
}

/** Fetch enrichment for a single element (query-on-select). */
export async function getElementEnrichment(path: string): Promise<ElementEnrichment | null> {
	try {
		const response = await sendQuery({
			id: `get_element_enrichment_${Date.now()}`,
			action: 'get_element_enrichment',
			path
		});
		return response.ok ? (response.data as ElementEnrichment) : null;
	} catch {
		return null;
	}
}

// ================================
// Export Functions
// ================================

export interface ExportOptions {
	outputPath: string;
	jobId?: string;
	fullPaths?: boolean;
	dbName?: string;
	deletionOnly?: boolean;
	/** 'csv' (default), 'resip' (SEDA archival CSV), 'xlsx' (Excel workbook),
	 *  or 'docx' (French audit report). */
	format?: 'csv' | 'resip' | 'xlsx' | 'docx';
}

/**
 * Export scan results to CSV file.
 * @param options - Export options including output path and database name
 */
export async function exportCsv(options: ExportOptions): Promise<CommandResult> {
	return await invoke<CommandResult>('export_csv', { options });
}

/**
 * Open a save file dialog for CSV export.
 * Returns the selected file path or null if cancelled.
 */
export async function selectExportPath(
	type: string = 'export',
	extension: string = 'csv',
	filterName: string = 'CSV',
	baseDir?: string
): Promise<string | null> {
	const { save } = await import('@tauri-apps/plugin-dialog');
	// Human-readable local date-time in the name (YYYY-MM-DD_HH-MM-SS) — readable at a glance and
	// still unique per export, instead of a raw epoch number.
	const d = new Date();
	const p = (n: number) => String(n).padStart(2, '0');
	const stamp = `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}-${p(d.getSeconds())}`;
	const fileName = `archifiltre-${type}-${stamp}.${extension}`;
	// When a base directory is given (the logs export anchors at Downloads), pre-fill the FULL
	// path so the Save-As dialog opens there every time — instead of the OS's last-used location.
	// Other exports pass no baseDir, so their behaviour is unchanged (filename only).
	let defaultPath = fileName;
	if (baseDir) {
		try {
			const { join } = await import('@tauri-apps/api/path');
			defaultPath = await join(baseDir, fileName);
		} catch {
			/* couldn't resolve → fall back to filename-only (OS default location) */
		}
	}
	const result = await save({
		title: 'Export scan results',
		defaultPath,
		filters: [{ name: filterName, extensions: [extension] }]
	});
	return result;
}

// ================================
// Tree Hierarchy Helpers
// ================================

/**
 * Build a map of parent path -> children for tree navigation.
 */
export function buildTreeHierarchy(directories: DirectoryNode[]): Map<string, DirectoryNode[]> {
	const childrenMap = new Map<string, DirectoryNode[]>();

	for (const dir of directories) {
		const parentPath = dir.path.includes('/')
			? dir.path.substring(0, dir.path.lastIndexOf('/'))
			: '';

		if (!childrenMap.has(parentPath)) {
			childrenMap.set(parentPath, []);
		}
		childrenMap.get(parentPath)!.push(dir);
	}

	// Sort children by size (largest first)
	for (const children of childrenMap.values()) {
		children.sort((a, b) => b.total_size - a.total_size);
	}

	return childrenMap;
}

/**
 * Get children of a directory path.
 */
export function getChildren(
	path: string,
	childrenMap: Map<string, DirectoryNode[]>
): DirectoryNode[] {
	return childrenMap.get(path) ?? [];
}

/**
 * Get root directories (those at minimum depth).
 */
export function getRootDirectories(directories: DirectoryNode[]): DirectoryNode[] {
	if (directories.length === 0) return [];
	const minDepth = Math.min(...directories.map((d) => d.depth));
	return directories
		.filter((d) => d.depth === minDepth)
		.sort((a, b) => b.total_size - a.total_size);
}

/**
 * Generate a color for a directory path.
 */
export function getColorForPath(path: string, isDirectory: boolean): string {
	if (!isDirectory) return '#6b7280'; // gray for files

	// Hash the path to get a consistent color
	let hash = 0;
	for (let i = 0; i < path.length; i++) {
		hash = path.charCodeAt(i) + ((hash << 5) - hash);
	}

	// Use HSL for better color distribution
	const hue = Math.abs(hash) % 360;
	const saturation = 65 + (Math.abs(hash >> 8) % 20); // 65-85%
	const lightness = 45 + (Math.abs(hash >> 16) % 15); // 45-60%

	return `hsl(${hue}, ${saturation}%, ${lightness}%)`;
}

// ================================
// Command Functions - Window Management
// ================================

/**
 * Create a new application window.
 * Each window is independent and manages its own tabs.
 * @returns The window ID of the newly created window
 */
export async function createWindow(): Promise<string> {
	return await invoke<string>('create_window');
}

// ================================
// Utility Functions
// ================================

/**
 * Format bytes into a human-readable string.
 */
export function formatBytes(bytes: number): string {
	if (bytes === 0) return '0 B';
	const units = ['B', 'KB', 'MB', 'GB', 'TB'];
	const k = 1024;
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return `${(bytes / Math.pow(k, i)).toFixed(i > 0 ? 1 : 0)} ${units[i]}`;
}

/**
 * Format a number with locale-specific thousand separators.
 */
export function formatNumber(num: number): string {
	return num.toLocaleString();
}

/**
 * Generate a unique identifier for scans/tabs.
 * Uses crypto.randomUUID() which is available in all modern browsers.
 */
export function generateId(): string {
	return crypto.randomUUID();
}
